server:
  port: 8082
  
logging:
  level:
    root: INFO
    io.junq: DEBUG 
    org.springframework.security: INFO

info:
  app:
    name: user-center-api
  build:
    version: @project.version@    

management:
  security:
    enabled: false
  context-path: /management
    
security:
  oauth2:
    resource:
      filter-order: 3